apiVersion: v1
kind: Service
metadata:
  name: minio-service-lb
  namespace: minio
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - name: service
      port: 19000
      targetPort: 9000
    - name: console
      port: 19001
      targetPort: 9001