apiVersion: v1
kind: Service
metadata:
  name: onnasoft-odoo-api-service
  namespace: onnasoft-odoo
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: service
      port: 18000
      targetPort: 3000
